[versions]
# Build & Kotlin
#noinspection AndroidGradlePluginVersion
agp = "8.5.1"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.22" # Deve casar com a vers√£o do Kotlin
#noinspection GradleDependency,GradleDependency
desugar = "2.0.4"

# Android Core & Compose
#noinspection GradleDependency
coreKtx = "1.13.1"
#noinspection GradleDependency,GradleDependency
lifecycle = "2.8.3"
#noinspection GradleDependency
activityCompose = "1.9.0"
#noinspection GradleDependency
composeBom = "2024.06.00"
#noinspection GradleDependency
navigationCompose = "2.7.7"
#noinspection GradleDependency
material3 = "1.2.1"
#noinspection GradleDependency
materialComponents = "1.12.0" # XML Legacy support if needed
#noinspection GradleDependency
splashScreen = "1.0.1"

# Architecture
hilt = "2.51.1"
#noinspection GradleDependency,GradleDependency,GradleDependency
androidxHilt = "1.2.0"
#noinspection GradleDependency
workRuntimeKtx = "2.9.0"
#noinspection GradleDependency
datastore = "1.1.1"

# Data & Network
retrofit = "2.11.0"
okhttp = "4.12.0"
kotlinxSerialization = "1.7.1"
kotlinxCollections = "0.3.7"
coil = "2.6.0"

# Testing
junit = "4.13.2"
#noinspection GradleDependency
junitVersion = "1.1.5"
#noinspection GradleDependency
espresso = "3.6.1"
coroutines = "1.8.1"

[libraries]
# Android Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

# Lifecycle & Navigation
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "materialComponents" } # Theme Fix

# Hilt (DI)
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }

# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

# Data & Networking
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollections" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version = "1.0.0" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" } # New in Kotlin 2.0
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]
compose = [
    "androidx-ui", 
    "androidx-ui-graphics", 
    "androidx-ui-tooling-preview", 
    "androidx-material3", 
    "androidx-material-icons-extended", 
    "coil-compose",
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-navigation-compose"
]
networking = ["retrofit-core", "retrofit-converter-kotlinx", "okhttp-logging"]
testing = ["junit", "androidx-junit", "androidx-espresso-core", "androidx-ui-test-junit4", "kotlinx-coroutines-test"]
debug-testing = ["androidx-ui-tooling", "androidx-ui-test-manifest"]